export const PROJECT_FORM = 'PROJECT_FORM';
export const GET_PROJECTS = 'GET_PROJECTS';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const CURRENT_PROJECT = 'CURRENT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const TASKS_PROJECT = 'TASKS_PROJECT';
export const CREATE_TASK = 'CREATE_TASK';
export const VALIDATE_TASK = 'VALIDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const STATUS_TASK = 'STATUS_TASK';
export const CURRENT_TASK = 'CURRENT_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const CLEAN_TASK = 'CLEAN_TASK';